name: Security Scans
on:
  pull_request:
    branches:
      - develop
      - main

  workflow_call:

jobs:
  scan-bandit:
    uses: intel-innersource/frameworks.ai.infrastructure.code-scan-tools/.github/workflows/Scanner_Bandit.yml@one-ci-cd
    with:
      org: intel-innersource
      repo: frameworks.ai.explainable-ai
      refs: ${{ github.head_ref }}
      config_file: bandit.yaml
      runners: "['xai-tlt']"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
