name: Style Check and Lint
on:
  pull_request:
    types: [submitted]
  # run the workflow if changes pushed to main or release branches
  push:
    branches: '**'
    paths: '**'

jobs:
  stylecheck-lint:
    name: Check codestsyle
    runs-on: [ xai-tlt ]
    container:
      image: ${{ vars.GHA_IMAGE }}
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      # credentials:
      #   username: ${{ secrets.REGISTRY_USER }}
      #   password: ${{ secrets.REGISTRY_TOKEN }}
      volumes:
        - /tf_dataset/dataset/transfer_learning:/tmp/data
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.1
      - name: Run stylecheck
        run: make stylecheck
